PORT: 8000
PREFIX: api

# 正常token2小时
tokenExpire: 2
# 刷新过期时间为7天
refreshTokenExpire: 7

# 默认密码
defaultPassword: 123456

# 数据库配置
datasource:
  driverName: mysql
  host: localhost
  port: 3306
  database: nestjs-mysql-api
  username: root
  password: 123456
  charset: utf8mb4
  loc: Asia/Shanghai
  logging: true

# redis
redis:
  port: 6379
  host: 127.0.0.1
  password: 123456
  db: 0

# rabbitmq
rabbitmq:
  uri: 'amqp://baigao:123456@localhost:5672'

