PORT: 8000
PREFIX: api

# 正常token2小时
tokenExpire: 2
# 刷新过期时间为7天
refreshTokenExpire: 7

          
# 数据库配置
db:
  host: 'localhost'
  port: 61850
  username: 'root'
  password: '123456'
  database: 'adplatform'
  prefix: 'ecs_'

# redis
redis:
  port: 6379
  host: 127.0.0.1
  password: 123456
  db: 0

# rabbitmq
rabbitmq:
  uri: 'amqp://guest:guest@localhost:5672'

